// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.CompanyLookup
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("ticker")]
        public string Ticker { get; set; }

        [JsonProperty("cik")]
        public string Cik { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("tickers")]
        public string[] Tickers { get; set; }

        [JsonProperty("exchanges")]
        public string[] Exchanges { get; set; }

        [JsonProperty("entityType")]
        public string EntityType { get; set; }

        [JsonProperty("sic")]
        public long Sic { get; set; }

        [JsonProperty("sicDescription")]
        public string SicDescription { get; set; }

        [JsonProperty("category")]
        public string Category { get; set; }

        [JsonProperty("stateOfIncorporation")]
        public string StateOfIncorporation { get; set; }

        [JsonProperty("fiscalYearEnd")]
        public string FiscalYearEnd { get; set; }

        [JsonProperty("ein")]
        public long Ein { get; set; }

        [JsonProperty("phone")]
        public string Phone { get; set; }

        [JsonProperty("addresses")]
        public Addresses Addresses { get; set; }

        [JsonProperty("formerNames")]
        public object[] FormerNames { get; set; }
    }

    public partial class Addresses
    {
        [JsonProperty("mailing")]
        public Business Mailing { get; set; }

        [JsonProperty("business")]
        public Business Business { get; set; }
    }

    public partial class Business
    {
        [JsonProperty("street1")]
        public string Street1 { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("stateOrCountry")]
        public string StateOrCountry { get; set; }

        [JsonProperty("zipCode")]
        public long ZipCode { get; set; }
    }
}
